# Statically link the MSVC/UCRT runtime so remote-agent.exe runs on fresh Windows
# without requiring a separate VC++ Redistributable install.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.i686-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
